# Generated by Django 4.2.9 on 2024-01-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_historicalperformance_average_response_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='completed_ontime',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
