# Generated by Django 4.2.9 on 2024-01-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_purchaseorder_completed_ontime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='completed_ontime',
            new_name='delivered_ontime',
        ),
    ]
