# Generated by Django 4.2.9 on 2024-01-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_rename_completed_ontime_purchaseorder_delivered_ontime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivered_ontime',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
